# Generated by Django 5.1.4 on 2024-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
